; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "POS"
!define PRODUCT_VERSION "2.0"
!define PRODUCT_PUBLISHER "S4D"
!define PRODUCT_WEB_SITE "https://s4d.eu/"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\AppMainExe.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "s4d logo.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
!insertmacro MUI_PAGE_LICENSE "..\Desktop\testlicentie.txt"
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN '"C:\ProgramFiles\Google\Chrome\Application\chrome.exe"'
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "English"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "Setup S4D.exe"
InstallDir "C:\temp"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Section "MainSection" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite ifnewer
  CreateDirectory "$SMPROGRAMS\POS"
  CreateShortCut "$SMPROGRAMS\POS\POS.lnk" "$INSTDIR\AppMainExe.exe"
  CreateShortCut "$DESKTOP\POS.lnk" "$INSTDIR\AppMainExe.exe"
SectionEnd

Section "Wkhtml64" SEC03
 File "..\Desktop\Store installation folder\Prerequisites\temp\wkhtmltox-0.12.6-1.msvc2015-win64.exe"
 ExecWait '"$INSTDIR\wkhtmltox-0.12.6-1.msvc2015-win64.exe" /S'
SectionEnd

Section "Wkhtml32" SEC04
 File "..\Desktop\Store installation folder\Prerequisites\temp\wkhtmltox-0.12.6-1.msvc2015-win32.exe"
 ExecWait '"$INSTDIR\wkhtmltox-0.12.6-1.msvc2015-win32.exe" /S'
SectionEnd

Section "OpenDRW.exe" SEC05
 File "..\Desktop\Store installation folder\Prerequisites\temp\OpenDRW.exe"
 ExecWait '"$INSTDIR\OpenDRW.exe" /quiet /install /norestart'
SectionEnd

Section "NDP472" SEC06
 File "..\Desktop\Store installation folder\Prerequisites\temp\NDP472-KB4054530-x86-x64-AllOS-ENU.exe"
 ExecWait '"$INSTDIR\NDP472-KB4054530-x86-x64-AllOS-ENU.exe" /quiet /install /norestart'
SectionEnd

Section "FoxitReader" SEC07
 File "..\Desktop\Store installation folder\Prerequisites\temp\FoxitReader971_enu_Setup_Prom.exe"
 ExecWait '"$INSTDIR\FoxitReader971_enu_Setup_Prom.exe" /verysilent /install /norestart DESKTOP_SHORTCUT=0" MAKEDEFAULT="0" VIEWINBROWSER="0" LAUNCHCHECKDEFAULT="0" AUTO_UPDATE="0" /NORESTART /D=C:\Program Files\Foxit Software}'
SectionEnd

Section "Dotnet6.0.8" SEC08
 File "..\Desktop\Store installation folder\Prerequisites\temp\dotnet-hosting-6.0.8-win.exe"
 ExecWait '"$INSTDIR\dotnet-hosting-6.0.8-win.exe" /quiet /install /norestart'
SectionEnd

Section "Dotnet6.0.5" SEC09
 File "..\Desktop\Store installation folder\Prerequisites\temp\dotnet-hosting-6.0.5-win.exe"
 ExecWait '"$INSTDIR\dotnet-hosting-6.0.5-win.exe" /quiet /install /norestart'
SectionEnd

Section "Dotnet5.0.6" SEC10
 File "..\Desktop\Store installation folder\Prerequisites\temp\dotnet-hosting-5.0.6-win.exe"
 ExecWait '"$INSTDIR\dotnet-hosting-5.0.6-win.exe" /quiet /install /norestart'
SectionEnd

Section "Dotnet3.1.11" SEC11
 File "..\Desktop\Store installation folder\Prerequisites\temp\dotnet-hosting-3.1.11-win.exe"
 ExecWait '"$INSTDIR\dotnet-hosting-3.1.11-win.exe" /quiet /install /norestart'
SectionEnd

Section "UninstallNET" SEC12
  Delete "$INSTDIR\dotnet-hosting-3.1.11-win.exe"
  Delete "$INSTDIR\dotnet-hosting-5.0.6-win.exe"
  Delete "$INSTDIR\dotnet-hosting-6.0.5-win.exe"
  Delete "$INSTDIR\dotnet-hosting-6.0.8-win.exe"
SectionEnd

Section "Net48" SEC13
 File "ndp48-web.exe"
 ExecWait '"$INSTDIR\ndp48-web.exe" /S /quiet /install /norestart'
SectionEnd

Section "Net481" SEC14
 File "NDP481-Web.exe"
 ExecWait '"$INSTDIR\NDP481-Web.exe" /S /quiet /install /norestart'
SectionEnd

Section "Chrome with POS" SEC17
  File "ChromeStandaloneSetup64.exe"
  ExecWait '"ChromeStandaloneSetup64.exe" /S /install'
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\AppMainExe.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\AppMainExe.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) was successfully removed from your computer."
FunctionEnd

Function un.onInit
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "Are you sure you want to completely remove $(^Name) and all of its components?" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\ChromeStandaloneSetup64.exe"
  Delete "$INSTDIR\Bakker Bart Device Hub Agent-1.0.791 Setup.exe"
  Delete "$INSTDIR\NDP481-Web.exe"
  Delete "$INSTDIR\ndp48-web.exe"
  Delete "$INSTDIR\dotnet-hosting-3.1.11-win.exe"
  Delete "$INSTDIR\dotnet-hosting-5.0.6-win.exe"
  Delete "$INSTDIR\dotnet-hosting-6.0.5-win.exe"
  Delete "$INSTDIR\dotnet-hosting-6.0.8-win.exe"
  Delete "$INSTDIR\FoxitReader971_enu_Setup_Prom.exe"
  Delete "$INSTDIR\NDP472-KB4054530-x86-x64-AllOS-ENU.exe"
  Delete "$INSTDIR\OpenDRW.exe"
  Delete "$INSTDIR\wkhtmltox-0.12.6-1.msvc2015-win32.exe"
  Delete "$INSTDIR\wkhtmltox-0.12.6-1.msvc2015-win64.exe"
  Delete "$INSTDIR\Example.file"
  Delete "$INSTDIR\AppMainExe.exe"

  Delete "$DESKTOP\POS.lnk"
  Delete "$SMPROGRAMS\POS\POS.lnk"

  RMDir "$SMPROGRAMS\POS"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd